# Use the official Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy Poetry files and install dependencies
COPY pyproject.toml poetry.lock* /app/
RUN poetry install --no-root

# Copy the application code
COPY ./app/ /app/app/

# Expose the port
EXPOSE 8080

# Run the FastAPI app
CMD ["poetry", "run", "uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8080","--proxy-headers"]

